[workspace]
resolver = "2"
members = [
  "crates/*"
]

[workspace.package]
version = "0.0.8"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unavi-xyz/bevy_vrm"
edition = "2021"

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.dependencies]
bevy = { version = "0.13.0", default-features = false, features = ["animation", "bevy_asset", "bevy_scene", "bevy_pbr"] }
bevy_shader_mtoon = { path = "crates/bevy_shader_mtoon", version = "0.0.8" }
gltf_kun = { version = "0.0.11", default-features = false }
gltf_kun_vrm = { path = "crates/gltf_kun_vrm", version = "0.0.8" }
serde = { version = "1.0.197", features = ["derive"] }
serde_vrm = { path = "crates/serde_vrm", version = "0.0.8" }
thiserror = "1.0.57"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
