[package]
name = "bevy_vrm"
version = "0.0.0"
license = "GPL-3.0-or-later"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
codegen-units = 1
