[workspace]
resolver = "2"
members = [
  "bevy_vrm",
  "bevy_shader_mtoon",
]

[workspace.package]
version = "0.0.8"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unavi-xyz/bevy_vrm"
edition = "2021"

[workspace.lints.clippy]
type_complexity = "allow"

[workspace.dependencies]
bevy = "0.13.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
