[package]
name = "bevy_vrm"
description = "Bevy plugin for loading VRM avatars."
version = "0.0.5"
license = "MIT OR Apache-2.0"
repository = "https://github.com/unavi-xyz/bevy_vrm"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true

[profile.wasm-release]
inherits = "release"
opt-level = 'z'

[dependencies]
bevy = "0.12.0"
bevy_shader_mtoon = "0.0.3"
goth-gltf = "0.1.1"
nanoserde = "0.1.35"
thiserror = "1.0"
