[package]
name = "bevy_shader_mtoon"
description = "Bevy MToon shader."
keywords = ["bevy", "shader", "toon"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
bitflags = "2.4.2"

[dev-dependencies]
bevy = "0.13.0"
bevy_panorbit_camera.workspace = true
