[package]
name = "bevy_shader_mtoon"
description = "Bevy MToon shader."
keywords = ["bevy", "shader", "toon"]
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
bevy.workspace = true
